# MODEL PROPERTIES
model_name: FasterRCNN-ResNet50-OD  # Name of the detection model, which should be trained. See the list at the bottom of this page for all the supported models.
pretrained_weights_path: ./model_weights/final_model.pth # Path to a model weights file, which should be used for fine-tuning the detector.

# GPU SETTINGS
gpu_id: 1  # The integer ID of the GPU, which should be used for training. Only single-GPU training currently supported.
num_workers: 2  # Amount of sub-processes for loading the data.

# DATASET PARAMETERS
dataset: KIA  # Name of the dataset, which should be used for training. Options: KIA or CityPersons.
data_path: /data/ai_data_and_models/KIA/KIA_LaG # Path to the dataset root folder.

# PEDESTRIAN HYPERPARAMETERS
min_obj_pixels: 1  # Filter out all pedestrian instances (during training) that have a lower amount of visible instance pixels than here specified. Must be an integer number greater or equal to zero. Used to filter out small or heavily occluded pedestrians with a too low amount of visible instance pixels. Set this to 1 to include all visible pedestrian instances during training.
min_occl: 0.0  # Filter out all pedestrian instances (during training) that have a lower occlusion rate than here specified. Must be a float number between 0 and 1.0.
max_occl: 0.01  # Filter out all pedestrian instances (during training) that have a higher occlusion rate than here specified. Must be a float number between 0 and 1.0. Higher values mean that samples with higher occlusions are included during training. Set this to 0.99 to include all visible pedestrian instances during training (1.0 means fully occluded and not visible at all).
max_distance: 500  # Filter out all pedestrian instances (during training) that have a higher distance than here specified. Must be an integer number greater or equal to zero, that specifies the distance in meters. Set this to 100 to include all pedestrian instances during training for the KIA dataset (100 meters is the highest annotated distance value).

# HYPERPARAMETERS FOR TRAINING SET
batch_size: 1  # Amount of training images per batch.
seed: 1  # Seed for the random module (used for reproducibility).