# EVALUATION PARAMETERS
model_name: ResNet18  # Name of the classification model being targeted for the attack. See the list at the bottom of this page for all the supported models.
weights_path: /path/to/weights.pt  # Path to the model weights file of the victim model.
attack_path: /path/to/attack_folder  # Path to the attack folder, which was generated after executing realistic_sticker_attack.py.
csv_path: /path/to/performance_evaluation.csv  # Destination path for the csv file, which will contain the evaluation results.
data_path: /path/to/pickled_data  # Path to the pickled_data folder containing the train.p, valid.p and test.p files.
dataset: test  # Specifies, which dataset should be used for the evaluation. Options: train, valid or test.
device_ids: '0'  # GPU index values for validating on multiple GPUs (e.g. '0,1,3'). Irrelevant if validating on cpu.


# List of supported models:
# VGG16
# VGG19
# InceptionV3
# ResNet18
# ResNet50
# ResNet101
# ResNet152
# WideResNet50
# WideResNet101
# ResNeXt50
# ResNeXt101