# EVALUATION PARAMETERS
model_name: ResNeXt101  # Name of the classification model, which is being evaluated. See the list at the bottom of this page for all the supported models.
weights_path: /path/to/weights.pt  # Path to the model weights file, which is being evaluated.
data_path: /path/to/data  # Path to the dataset folder, where the pickled_data folder is located.
dataset: test  # Specifies, which dataset should be used for the evaluation. Options: train, valid or test.
batch_size: 64  # Amount of evaluation images per batch.
device_ids: '3'  # GPU index values for evaluating on multiple GPUs (e.g. '0,1,3'). Irrelevant if evaluating on CPU.
num_classes: 43

# List of supported models:
# VGG16
# VGG19
# InceptionV3
# ResNet18
# ResNet50
# ResNet101
# ResNet152
# WideResNet50
# WideResNet101
# ResNeXt50
# ResNeXt101